// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package com.epam.eco.kafkamanager.ui.browser.protobuf;

public interface ProtobufRecordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kafkaManager.test.ProtobufRecord)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string operationId = 1;</code>
   * @return Whether the operationId field is set.
   */
  boolean hasOperationId();
  /**
   * <code>required string operationId = 1;</code>
   * @return The operationId.
   */
  java.lang.String getOperationId();
  /**
   * <code>required string operationId = 1;</code>
   * @return The bytes for operationId.
   */
  com.google.protobuf.ByteString
      getOperationIdBytes();

  /**
   * <code>required int32 docId = 2;</code>
   * @return Whether the docId field is set.
   */
  boolean hasDocId();
  /**
   * <code>required int32 docId = 2;</code>
   * @return The docId.
   */
  int getDocId();

  /**
   * <code>optional string metadataTt = 3;</code>
   * @return Whether the metadataTt field is set.
   */
  boolean hasMetadataTt();
  /**
   * <code>optional string metadataTt = 3;</code>
   * @return The metadataTt.
   */
  java.lang.String getMetadataTt();
  /**
   * <code>optional string metadataTt = 3;</code>
   * @return The bytes for metadataTt.
   */
  com.google.protobuf.ByteString
      getMetadataTtBytes();

  /**
   * <code>optional string metadataBt = 4;</code>
   * @return Whether the metadataBt field is set.
   */
  boolean hasMetadataBt();
  /**
   * <code>optional string metadataBt = 4;</code>
   * @return The metadataBt.
   */
  java.lang.String getMetadataBt();
  /**
   * <code>optional string metadataBt = 4;</code>
   * @return The bytes for metadataBt.
   */
  com.google.protobuf.ByteString
      getMetadataBtBytes();
}
