// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package com.epam.eco.kafkamanager.ui.browser.protobuf;

/**
 * Protobuf type {@code kafkaManager.test.ProtobufRecord}
 */
public final class ProtobufRecord extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:kafkaManager.test.ProtobufRecord)
    ProtobufRecordOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProtobufRecord.newBuilder() to construct.
  private ProtobufRecord(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProtobufRecord() {
    operationId_ = "";
    metadataTt_ = "";
    metadataBt_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProtobufRecord();
  }

  @java.lang.Override
  public com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ProtobufRecord(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            operationId_ = bs;
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            docId_ = input.readInt32();
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000004;
            metadataTt_ = bs;
            break;
          }
          case 34: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000008;
            metadataBt_ = bs;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.epam.eco.kafkamanager.ui.browser.protobuf.Schema.internal_static_kafkaManager_test_ProtobufRecord_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.epam.eco.kafkamanager.ui.browser.protobuf.Schema.internal_static_kafkaManager_test_ProtobufRecord_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.epam.eco.kafkamanager.ui.browser.protobuf.ProtobufRecord.class, com.epam.eco.kafkamanager.ui.browser.protobuf.ProtobufRecord.Builder.class);
  }

  private int bitField0_;
  public static final int OPERATIONID_FIELD_NUMBER = 1;
  private volatile java.lang.Object operationId_;
  /**
   * <code>required string operationId = 1;</code>
   * @return Whether the operationId field is set.
   */
  @java.lang.Override
  public boolean hasOperationId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required string operationId = 1;</code>
   * @return The operationId.
   */
  @java.lang.Override
  public java.lang.String getOperationId() {
    java.lang.Object ref = operationId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        operationId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string operationId = 1;</code>
   * @return The bytes for operationId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOperationIdBytes() {
    java.lang.Object ref = operationId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      operationId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DOCID_FIELD_NUMBER = 2;
  private int docId_;
  /**
   * <code>required int32 docId = 2;</code>
   * @return Whether the docId field is set.
   */
  @java.lang.Override
  public boolean hasDocId() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required int32 docId = 2;</code>
   * @return The docId.
   */
  @java.lang.Override
  public int getDocId() {
    return docId_;
  }

  public static final int METADATATT_FIELD_NUMBER = 3;
  private volatile java.lang.Object metadataTt_;
  /**
   * <code>optional string metadataTt = 3;</code>
   * @return Whether the metadataTt field is set.
   */
  @java.lang.Override
  public boolean hasMetadataTt() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string metadataTt = 3;</code>
   * @return The metadataTt.
   */
  @java.lang.Override
  public java.lang.String getMetadataTt() {
    java.lang.Object ref = metadataTt_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        metadataTt_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string metadataTt = 3;</code>
   * @return The bytes for metadataTt.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMetadataTtBytes() {
    java.lang.Object ref = metadataTt_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      metadataTt_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METADATABT_FIELD_NUMBER = 4;
  private volatile java.lang.Object metadataBt_;
  /**
   * <code>optional string metadataBt = 4;</code>
   * @return Whether the metadataBt field is set.
   */
  @java.lang.Override
  public boolean hasMetadataBt() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional string metadataBt = 4;</code>
   * @return The metadataBt.
   */
  @java.lang.Override
  public java.lang.String getMetadataBt() {
    java.lang.Object ref = metadataBt_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        metadataBt_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string metadataBt = 4;</code>
   * @return The bytes for metadataBt.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMetadataBtBytes() {
    java.lang.Object ref = metadataBt_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      metadataBt_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasOperationId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasDocId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, operationId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt32(2, docId_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, metadataTt_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, metadataBt_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, operationId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, docId_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, metadataTt_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, metadataBt_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ProtobufRecord other)) {
      return super.equals(obj);
    }

      if (hasOperationId() != other.hasOperationId()) return false;
    if (hasOperationId()) {
      if (!getOperationId()
          .equals(other.getOperationId())) return false;
    }
    if (hasDocId() != other.hasDocId()) return false;
    if (hasDocId()) {
      if (getDocId()
          != other.getDocId()) return false;
    }
    if (hasMetadataTt() != other.hasMetadataTt()) return false;
    if (hasMetadataTt()) {
      if (!getMetadataTt()
          .equals(other.getMetadataTt())) return false;
    }
    if (hasMetadataBt() != other.hasMetadataBt()) return false;
    if (hasMetadataBt()) {
      if (!getMetadataBt()
          .equals(other.getMetadataBt())) return false;
    }
    return unknownFields.equals(other.unknownFields);
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasOperationId()) {
      hash = (37 * hash) + OPERATIONID_FIELD_NUMBER;
      hash = (53 * hash) + getOperationId().hashCode();
    }
    if (hasDocId()) {
      hash = (37 * hash) + DOCID_FIELD_NUMBER;
      hash = (53 * hash) + getDocId();
    }
    if (hasMetadataTt()) {
      hash = (37 * hash) + METADATATT_FIELD_NUMBER;
      hash = (53 * hash) + getMetadataTt().hashCode();
    }
    if (hasMetadataBt()) {
      hash = (37 * hash) + METADATABT_FIELD_NUMBER;
      hash = (53 * hash) + getMetadataBt().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.epam.eco.kafkamanager.ui.browser.protobuf.ProtobufRecord parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.epam.eco.kafkamanager.ui.browser.protobuf.ProtobufRecord parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.epam.eco.kafkamanager.ui.browser.protobuf.ProtobufRecord parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.epam.eco.kafkamanager.ui.browser.protobuf.ProtobufRecord parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.epam.eco.kafkamanager.ui.browser.protobuf.ProtobufRecord parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.epam.eco.kafkamanager.ui.browser.protobuf.ProtobufRecord parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.epam.eco.kafkamanager.ui.browser.protobuf.ProtobufRecord parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.epam.eco.kafkamanager.ui.browser.protobuf.ProtobufRecord parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.epam.eco.kafkamanager.ui.browser.protobuf.ProtobufRecord parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.epam.eco.kafkamanager.ui.browser.protobuf.ProtobufRecord parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.epam.eco.kafkamanager.ui.browser.protobuf.ProtobufRecord parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.epam.eco.kafkamanager.ui.browser.protobuf.ProtobufRecord parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.epam.eco.kafkamanager.ui.browser.protobuf.ProtobufRecord prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code kafkaManager.test.ProtobufRecord}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:kafkaManager.test.ProtobufRecord)
      com.epam.eco.kafkamanager.ui.browser.protobuf.ProtobufRecordOrBuilder {
    public static com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.epam.eco.kafkamanager.ui.browser.protobuf.Schema.internal_static_kafkaManager_test_ProtobufRecord_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.epam.eco.kafkamanager.ui.browser.protobuf.Schema.internal_static_kafkaManager_test_ProtobufRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.epam.eco.kafkamanager.ui.browser.protobuf.ProtobufRecord.class, com.epam.eco.kafkamanager.ui.browser.protobuf.ProtobufRecord.Builder.class);
    }

    // Construct using com.epam.eco.kafkamanager.ui.browser.protobuf.ProtobufRecord.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      operationId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      docId_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      metadataTt_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      metadataBt_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.epam.eco.kafkamanager.ui.browser.protobuf.Schema.internal_static_kafkaManager_test_ProtobufRecord_descriptor;
    }

    @java.lang.Override
    public com.epam.eco.kafkamanager.ui.browser.protobuf.ProtobufRecord getDefaultInstanceForType() {
      return com.epam.eco.kafkamanager.ui.browser.protobuf.ProtobufRecord.getDefaultInstance();
    }

    @java.lang.Override
    public com.epam.eco.kafkamanager.ui.browser.protobuf.ProtobufRecord build() {
      com.epam.eco.kafkamanager.ui.browser.protobuf.ProtobufRecord result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.epam.eco.kafkamanager.ui.browser.protobuf.ProtobufRecord buildPartial() {
      com.epam.eco.kafkamanager.ui.browser.protobuf.ProtobufRecord result = new com.epam.eco.kafkamanager.ui.browser.protobuf.ProtobufRecord(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.operationId_ = operationId_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.docId_ = docId_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.metadataTt_ = metadataTt_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        to_bitField0_ |= 0x00000008;
      }
      result.metadataBt_ = metadataBt_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.epam.eco.kafkamanager.ui.browser.protobuf.ProtobufRecord) {
        return mergeFrom((com.epam.eco.kafkamanager.ui.browser.protobuf.ProtobufRecord)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.epam.eco.kafkamanager.ui.browser.protobuf.ProtobufRecord other) {
      if (other == com.epam.eco.kafkamanager.ui.browser.protobuf.ProtobufRecord.getDefaultInstance()) return this;
      if (other.hasOperationId()) {
        bitField0_ |= 0x00000001;
        operationId_ = other.operationId_;
        onChanged();
      }
      if (other.hasDocId()) {
        setDocId(other.getDocId());
      }
      if (other.hasMetadataTt()) {
        bitField0_ |= 0x00000004;
        metadataTt_ = other.metadataTt_;
        onChanged();
      }
      if (other.hasMetadataBt()) {
        bitField0_ |= 0x00000008;
        metadataBt_ = other.metadataBt_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public boolean isInitialized() {
      if (!hasOperationId()) {
        return false;
      }
        return hasDocId();
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.epam.eco.kafkamanager.ui.browser.protobuf.ProtobufRecord parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.epam.eco.kafkamanager.ui.browser.protobuf.ProtobufRecord) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object operationId_ = "";
    /**
     * <code>required string operationId = 1;</code>
     * @return Whether the operationId field is set.
     */
    public boolean hasOperationId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string operationId = 1;</code>
     * @return The operationId.
     */
    public java.lang.String getOperationId() {
      java.lang.Object ref = operationId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          operationId_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string operationId = 1;</code>
     * @return The bytes for operationId.
     */
    public com.google.protobuf.ByteString
        getOperationIdBytes() {
      java.lang.Object ref = operationId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        operationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string operationId = 1;</code>
     * @param value The operationId to set.
     * @return This builder for chaining.
     */
    public Builder setOperationId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      operationId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string operationId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOperationId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      operationId_ = getDefaultInstance().getOperationId();
      onChanged();
      return this;
    }
    /**
     * <code>required string operationId = 1;</code>
     * @param value The bytes for operationId to set.
     * @return This builder for chaining.
     */
    public Builder setOperationIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      operationId_ = value;
      onChanged();
      return this;
    }

    private int docId_ ;
    /**
     * <code>required int32 docId = 2;</code>
     * @return Whether the docId field is set.
     */
    @java.lang.Override
    public boolean hasDocId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int32 docId = 2;</code>
     * @return The docId.
     */
    @java.lang.Override
    public int getDocId() {
      return docId_;
    }
    /**
     * <code>required int32 docId = 2;</code>
     * @param value The docId to set.
     * @return This builder for chaining.
     */
    public Builder setDocId(int value) {
      bitField0_ |= 0x00000002;
      docId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 docId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDocId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      docId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object metadataTt_ = "";
    /**
     * <code>optional string metadataTt = 3;</code>
     * @return Whether the metadataTt field is set.
     */
    public boolean hasMetadataTt() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string metadataTt = 3;</code>
     * @return The metadataTt.
     */
    public java.lang.String getMetadataTt() {
      java.lang.Object ref = metadataTt_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          metadataTt_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string metadataTt = 3;</code>
     * @return The bytes for metadataTt.
     */
    public com.google.protobuf.ByteString
        getMetadataTtBytes() {
      java.lang.Object ref = metadataTt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        metadataTt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string metadataTt = 3;</code>
     * @param value The metadataTt to set.
     * @return This builder for chaining.
     */
    public Builder setMetadataTt(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      metadataTt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string metadataTt = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMetadataTt() {
      bitField0_ = (bitField0_ & ~0x00000004);
      metadataTt_ = getDefaultInstance().getMetadataTt();
      onChanged();
      return this;
    }
    /**
     * <code>optional string metadataTt = 3;</code>
     * @param value The bytes for metadataTt to set.
     * @return This builder for chaining.
     */
    public Builder setMetadataTtBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      metadataTt_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object metadataBt_ = "";
    /**
     * <code>optional string metadataBt = 4;</code>
     * @return Whether the metadataBt field is set.
     */
    public boolean hasMetadataBt() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string metadataBt = 4;</code>
     * @return The metadataBt.
     */
    public java.lang.String getMetadataBt() {
      java.lang.Object ref = metadataBt_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          metadataBt_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string metadataBt = 4;</code>
     * @return The bytes for metadataBt.
     */
    public com.google.protobuf.ByteString
        getMetadataBtBytes() {
      java.lang.Object ref = metadataBt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        metadataBt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string metadataBt = 4;</code>
     * @param value The metadataBt to set.
     * @return This builder for chaining.
     */
    public Builder setMetadataBt(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      metadataBt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string metadataBt = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMetadataBt() {
      bitField0_ = (bitField0_ & ~0x00000008);
      metadataBt_ = getDefaultInstance().getMetadataBt();
      onChanged();
      return this;
    }
    /**
     * <code>optional string metadataBt = 4;</code>
     * @param value The bytes for metadataBt to set.
     * @return This builder for chaining.
     */
    public Builder setMetadataBtBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      metadataBt_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:kafkaManager.test.ProtobufRecord)
  }

  // @@protoc_insertion_point(class_scope:kafkaManager.test.ProtobufRecord)
  private static final com.epam.eco.kafkamanager.ui.browser.protobuf.ProtobufRecord DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.epam.eco.kafkamanager.ui.browser.protobuf.ProtobufRecord();
  }

  public static com.epam.eco.kafkamanager.ui.browser.protobuf.ProtobufRecord getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<ProtobufRecord>
      PARSER = new com.google.protobuf.AbstractParser<ProtobufRecord>() {
    @java.lang.Override
    public ProtobufRecord parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ProtobufRecord(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProtobufRecord> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProtobufRecord> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.epam.eco.kafkamanager.ui.browser.protobuf.ProtobufRecord getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

